select U.SYSUSER_NAME,D.DIC_NAME AS BUSTYPE,D2.DIC_NAME AS OBJTYPE from PLAT_SYSTEM_SECAUDIT t
LEFT JOIN PLAT_SYSTEM_SYSUSER U ON 
 T.SECAUDIT_USERID=U.SYSUSER_ID LEFT JOIN PLAT_SYSTEM_DICTIONARY D 
  ON T.SECAUDIT_BUSTYPE=D.DIC_VALUE AND D.DIC_DICTYPE_CODE='secbustype'
LEFT JOIN PLAT_SYSTEM_DICTIONARY D2 ON T.SECAUDIT_OBJTYPE=D2.DIC_VALUE AND D2.DIC_DICTYPE_CODE='secbusobjtype'
 where t.secaudit_id=?