select T.RES_ID,T.RES_NAME,T.RES_MENUURL,T.RES_MENUICON 
from PLAT_SYSTEM_RES T WHERE T.RES_STATUS = '1' AND T.RES_PARENTID=? AND T.RES_CODE IN
(select R.RES_CODE from PLAT_SYSTEM_RES R WHERE R.RES_STATUS = '1' AND R.RES_ID IN (
 SELECT T.RE_RECORDID FROM  PLAT_SYSTEM_ROLERIGHT T WHERE T.RE_TABLENAME='PLAT_SYSTEM_RES' AND (
 T.ROLE_ID IN (SELECT SR.ROLE_ID FROM PLAT_SYSTEM_SYSUSERROLE SR WHERE SR.SYSUSER_ID=? )
 OR (T.ROLE_ID =? AND T.ROLE_TABLE='PLAT_SYSTEM_SYSUSER')
OR (T.ROLE_ID=(SELECT U.SYSUSER_GROUPID FROM PLAT_SYSTEM_SYSUSER U WHERE U.SYSUSER_ID=?)
   AND T.ROLE_TABLE='PLAT_SYSTEM_USERGROUP' )
 )))
  AND T.RES_TYPE=? ORDER BY T.RES_TREESN ASC