 select T.LOG_ID,T.BROWSER,T.OPER_TIME,T.OPER_USERNAME,T.OPER_USERACCOUNT,T.IP_ADDRESS
,T.OPER_MODULENAME,D.DIC_NAME AS OPER_TYPE
 from PLAT_SYSTEM_SYSLOG T LEFT JOIN 
  PLAT_SYSTEM_DICTIONARY D ON T.OPER_TYPE=D.DIC_VALUE WHERE D.DIC_DICTYPE_CODE='OPER_TYPE'
  AND T.LOG_ID in 